#!/bin/bash

# Taken from https://juripakaste.fi/git-history-search-fzf
# Thanks a lot!

set -euo pipefail

# Ensure compatibility with fish etc by ensuring fzf uses bash for the preview command
export SHELL=/bin/bash

# Use smartcase (like in vim) for search:
# * check if there are uppercase letters in search regex
# * If so: Search case sensitive
# * if not: Search case insensitive
if [[ $@ =~ [A-Z] ]]; then
    CMD="git log"
else
    CMD="git log -i"
fi

# git log -G$@ -i --oneline | fzf \
$CMD -G$@ --oneline | fzf \
    --preview-window=bottom,80% \
    --preview "echo {} | sed 's/ .*//g' | xargs git show --color" \
    --bind 'enter:execute(commit=$(echo {} | sed "s/ .*//g") && git diff-tree --no-commit-id --name-only $commit -r | fzf --preview-window=bottom,80% --preview "git show --color $commit -- $(git rev-parse --show-toplevel)/\{}")'
